apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: primary-udn
  namespace: udn-vm
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  layer2:
    role: Primary
    subnets:
      - 192.168.10.1/24
    ipam:
      lifecycle: Persistent
      mode: Enabled
  topology: Layer2
