apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-vm
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-vm
  project: default
  source:
    path: templates/simple
    repoURL: https://github.com/too-common-name/ocp-virt-gitops.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true