apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: udn-vm
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: templates/l2-udn
    repoURL: https://github.com/too-common-name/ocp-virt-gitops.git
    targetRevision: HEAD