apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.ovn.org/network-name: br0-network
    argocd.argoproj.io/sync-wave: "4"
  name: ovn-localnet
  namespace: secondarynet-mnp
spec:
  config: |-
    {
        "cniVersion": "0.4.0",
        "name": "br0-network",
        "type": "ovn-k8s-cni-overlay",
        "netAttachDefName": "secondarynet-mnp/ovn-localnet",
        "topology": "localnet",
        "subnets": "192.168.200.0/24",
        "excludeSubnets": "192.168.200.0/29"
    }
