apiVersion: v1
items:
- apiVersion: k8s.cni.cncf.io/v1beta1
  kind: MultiNetworkPolicy
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/policy-for: secondarynet-mnp/ovn-localnet
      argocd.argoproj.io/sync-wave: "6"
    name: allow-tcp-8080-same-ns
    namespace: secondarynet-mnp
  spec:
    ingress:
    - from:
      - podSelector: {}
      ports:
      - port: 8080
        protocol: TCP
    podSelector:
      matchLabels:
        app: fedora-2
    policyTypes:
    - Ingress
- apiVersion: k8s.cni.cncf.io/v1beta1
  kind: MultiNetworkPolicy
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/policy-for: secondarynet-mnp/ovn-localnet
      argocd.argoproj.io/sync-wave: "6"
    name: deny-by-default-but-gw
    namespace: secondarynet-mnp
  spec:
    ingress:
    - from:
      - ipBlock:
          cidr: 192.168.200.1/32
          except: []
    podSelector: {}
    policyTypes:
    - Ingress
kind: List
metadata:
  resourceVersion: ""
